### ISSUE TITLE
Need to update to thread safe version of TMinuit

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/root#111]
We need to update our v6.08 copy to include the changes that make TMinuit safe. This includes the commits from Philippe up to this one
50ad534d1448c69635bbc3eea0f8fa2478fb6006

@smuzaffar @davidlange6 @davidlt

**Comment by Dr15Jones** [comment]
This was found because of problems seen in CMSSW_9_2_X IBs.

**Comment by smuzaffar** [comment]
@Dr15Jones , https://github.com/cms-sw/cmsdist/pull/3035 uses the tip of root v6-08-00-patches branch (i.e. https://github.com/root-project/root/commit/50ad534d1448c69635bbc3eea0f8fa2478fb6006 )

**Comment by Dr15Jones** [comment]
@smuzaffar thanks! There will be another change to ROOT coming soon since I found the exact reason for the crashes we've seen. I created a Jira ticket for the problem and Philippe is working on a fix.

**Comment by smuzaffar** [comment]
@Dr15Jones , can we close this?

**Comment by Dr15Jones** [comment]
It looks like the jira ticket was
https://sft.its.cern.ch/jira/projects/ROOT/issues/ROOT-8795

which says it was resolved. So we should be able to close this issue.
