### ISSUE TITLE
Conflict while cherry-picking.

### ISSUE THREAD

**Issue by gudrutis** [cms-sw/root#115]
@Dr15Jones @davidlt  @smuzaffar

I was trying to update root in CMSSW_9_4_ROOT6_X in sync with this root commit [1]. However I could not apply this commit [2] while cherry-picking . It looks like the context code referenced in the commit [2] was moved to a separate function [3].

@Dr15Jones, do we still need patch [2]. If yes, should we include it into [3] after shown line? Or you have any better suggestion? 

[1] https://github.com/root-project/root/commit/22da3bc7a13d15e3ba69a76be5c8dbe0499aa8e8
[2] https://github.com/cms-sw/root/commit/2474997db136cd8d2f2e15acb4ad7961d6b476dc?diff=unified#diff-8d36621ad8c8747b038c3b05fdd0c3adR90
[3] https://github.com/root-project/root/blob/2b690ee44992d58fcea38271fe689699ca6ea176/core/base/inc/TROOT.h#L387

**Comment by davidlt** [comment]
The change in ROOT was done 15 days ago, here is the commit: https://github.com/root-project/root/commit/fc0248d4c2db7b77415328d4d25ef1ed88265d37

IIRC this is the last piece that keep carrying from the original Chris patch. This still should be needed and you probably should put `R__LOCKGUARD2(gROOTMutex);` into if-statement in `core/base/inc/TROOT.h:386`, but wait for Chris confirmation.

**Comment by Dr15Jones** [comment]
It does appear that we do need the lock. I suggest adding the lock here:
https://github.com/root-project/root/blob/master/core/base/src/TROOT.cxx#L2393

Since we are protecting access to calls made to `TROOT::fCleanups` and that function is the one now making the call to that container.

**Comment by bbockelm** [comment]
We should have Philippe look at this.... there's been a huge amount of work in master toward making `TROOT::fCleanups` thread-safe.  Not sure what's landed and what hasn't, but would be a shame to overly serialize this if Philippe is done with his work.

**Comment by Dr15Jones** [comment]
@bbockelm I was looking at the master this morning and saw no signs of the `TROOT::fCleanups` thread safey change.

**Comment by bbockelm** [comment]
Sure - let's still poke Philippe to see where it stands!

**Comment by Dr15Jones** [comment]
I just talked with Philippe, the change you mention is still a work in progress. It might make 6.12 and it might not.

**Comment by gudrutis** [comment]
[This commit](https://github.com/cms-sw/root/commit/9f9b4067b3620037f9e6aa34513ad9287078e0ec) is based on your suggestion. Let me know if everything is done correctly.

**Comment by Dr15Jones** [comment]
The commit looks good.

**Comment by gudrutis** [comment]
Great. I am closing the issue then.
