### ISSUE TITLE
Update needed for CXXMODULEs IBs

### ISSUE THREAD

**Issue by smuzaffar** [cms-sw/root#126]
@oshadura and @yamaguchi1024 I am trying to update root for CXXMODULES IBs but couple of changes have merge conflicts. Can you please make a PR against https://github.com/cms-sw/root/tree/cmscxx/master/610a87c0a2 branch to include the following commits

- https://github.com/cms-sw/root/pull/125/commits/a29060e3db4b12a1cb09755370a96d2d854883d0
- https://github.com/cms-sw/root/pull/125/commits/cda2eb88424ea42ac8444c07066ee67b56e1af20

**Comment by oshadura** [comment]
@smuzaffar thank you for reminder! I am taking a look and will come back with PR.

**Comment by oshadura** [comment]
Here it is a new PR: https://github.com/cms-sw/root/pull/127
