### ISSUE TITLE
ROOT modules branch redundant commits

### ISSUE THREAD

**Issue by mrodozov** [cms-sw/root#137]
@vgvassilev @oshadura ,
getting the latest commits from root master on top of 
https://github.com/cms-sw/root/tree/cmscxx/master/7aa30ce1c8
resulted in conflict with this commit, 
https://github.com/cms-sw/root/commit/caba821a969cc05a0127fc34b4a5457c993433b9
which we skipped in 
https://github.com/cms-sw/root/tree/cmscxx/master/e1491c6

@smuzaffar told me you've mentioned in your comments some of this commits are not needed . would you please clarify which exactly

**Comment by vgvassilev** [comment]
You could modify the conflict and change:
```
3856    clang::Module *module = headerSearch.lookupModule(StringRef(moduleName));
```
to
```
  clang::Module *module = headerSearch.lookupModule(StringRef(moduleName), true, true);
```

We cannot say if we need this patch or not because the new modules setup for CMSSW seems severely broken. Until we fix it we have no way of verifying if something is redundant or not.

**Comment by smuzaffar** [comment]
@vgvassilev , we can not fix unless we know what is broken :-)

**Comment by vgvassilev** [comment]
@smuzaffar, that is what I am investigating. At the moment, if I enable modules for all of FWCore (excluding FWCore*Test) and start building the dictionary for DataFormats/Provenance, rootcling produces the wrong dictionary (even when it was called with no -cxxmodule flag). This means that we cannot activate the FWCore modules properly. I suspect it has something to do in how we write the modulemap file.

**Comment by mrodozov** [comment]
@vgvassilev 
I'll put the change back by hand since the conflict is due to recent file change, correct ?

**Comment by vgvassilev** [comment]
Yes, presumably updating the patch so that next time it applies.
