### ISSUE TITLE
Remove printout

### ISSUE THREAD

**Issue by kpedro88** [cms-sw/root#140]
This is now showing up (repeatedly) in step3 logs:
https://github.com/cms-sw/root/blob/cms/v6-20-00-patches/61f6828/tmva/tmva/src/DataSetInfo.cxx#L83

It was removed upstream by a later commit:
https://github.com/root-project/root/commit/d06eca184eca4c8b5b3b50f248db8b7ef5422448#diff-ce078182ab62d963d7111107058dfe97

If we're going to stick to that version of ROOT for a while, would be nice to get rid of it.

**Comment by smuzaffar** [comment]
this has been fixed https://github.com/root-project/root/commit/b1a51fa49a1f3cac9b16ca5fbd7d0fed782881a7#diff-257fae5c7dc2e836a18959084684792777e09654d475fcec4f3a41cbb6e67d0d
