### ISSUE TITLE
Update root to get threading improvement

### ISSUE THREAD

**Issue by Dr15Jones** [cms-sw/root#141]
It would be good to update our ROOT 6.20 to have the commits up to and including

https://github.com/root-project/root/commit/482d499d821b1b4f7b068be85e76dc5dc2f232cd

The related commits avoid contention on std::atomics which were found while measuring serialization performance.

**Comment by makortel** [comment]
assign core

**Comment by smuzaffar** [comment]
very old issue, this has been updated
