### ISSUE TITLE
Add fix from mainstream in root 5.34.22

### ISSUE THREAD

**Issue by ktf** [cms-sw/root#52]
We need to cherry-pick root-mirror/root@f221e1d51c0d33bf50540f18c3f11a75c865780b into our 5.34.22 branch.

**Comment by ktf** [comment]
@degano can you please look into this?

**Comment by degano** [comment]
@ktf I'm on it

**Comment by degano** [comment]
@ktf done in https://github.com/cms-sw/cmsdist/pull/1181.
